services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - BUILD_VERSION=${BUILD_VERSION:-dev}
    restart: unless-stopped

  caddy:
    image: caddy:2.11.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
